repos:
  - repo: https://github.com/psf/black.git
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8.git
    rev: 4.0.1
    hooks:
      - id: flake8
